# Stage 1: Build the Angular app
FROM node:18-alpine as build

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN npm run build --omit=dev --configuration=production

# Stage 2: Serve the app using Nginx
FROM nginx:stable-alpine

COPY --from=build /app/dist/capital-copilot-fe/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

