# Copyright (c) 2024 Perpetuator LLC

version: '3.7'

services:
  web:
    container_name: copilot_django
    build: .
    command: poetry run gunicorn copilot.wsgi:application --bind 0.0.0.0:8000
    volumes:
      #- .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "${COPILOT_DJANGO_PORT:-8000}:8000"
    restart: always

  nginx:
    container_name: copilot_nginx
    image: nginx:stable-alpine
    ports:
      - "${COPILOT_NGINX_PORT:-80}:80"
    environment:
      - VIRTUAL_HOST=copilot.perpetuator.com
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=copilot.perpetuator.com
      - LETSENCRYPT_EMAIL=nik@perpetuator.com
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media

volumes:
  static_volume:
  media_volume:

networks:
  default:
    name: nginx-proxy
