# Copyright (c) 2024 Perpetuator LLC
---
- name: Configure EC2 instance
  hosts: all
  tasks:
    #    - name: Stop Docker Compose
    #      shell: docker-compose down
    #      args:
    #        chdir: /home/ec2-user/

    - name: Start Docker Compose
      shell: docker-compose up -d
      args:
        chdir: /home/ec2-user/
